name: bias_propagation
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - scikit-image
  - pandas
  - nltk
  - py4j
  - pip
  - scikit-learn
  - pip:
    - certifi==2023.5.7
    - chardet==5.1.0
    - charset-normalizer==3.2.0
    - click==8.1.5
    - clip==1.0
    - filelock==3.12.2
    - fsspec==2023.6.0
    - ftfy==6.1.1
    - huggingface-hub==0.16.4
    - idna==3.4
    - jinja2==3.1.2
    - joblib==1.3.1
    - markupsafe==2.1.3
    - mpmath==1.3.0
    - networkx==3.1
    - numpy==1.25.1
    - packaging==23.1
    - pillow==10.0.0
    - regex==2023.6.3
    - requests==2.31.0
    - sacremoses==0.0.53
    - sympy==1.12
    - tokenizers==0.10.3
    - torch==2.0.1
    - torchvision==0.15.2
    - tqdm==4.65.0
    - transformers==4.10.3
    - typing-extensions==4.7.1
    - urllib3==2.0.3
    - wcwidth==0.2.6
